// ─────────────────────────────────────────────────────────────────────────────
// alphabetData.js — Complete letter data for all 6 supported scripts
// ─────────────────────────────────────────────────────────────────────────────

export const ALPHABETS = {
  english: {
    id: 'english',
    name: 'English',
    nativeName: 'English',
    accentClass: 'accent-english',
    color: '#6366f1',
    direction: 'ltr',
    langCode: 'en-US',        // BCP-47 for browser TTS voice selection
    voiceLang: 'en',          // short prefix for voice matching
    description: 'The Latin alphabet used for Modern English, consisting of 26 letters.',
    historicalNote: 'Derived from the Latin alphabet, which itself came from Greek via Etruscan. English uses 26 letters but relies heavily on digraphs for its rich sound system.',
    letters: [
      { id:'en-a', char:'A', lower:'a', name:'A', sound:'æ / eɪ', ipa:'/æ/', example:'Apple', examplePhonetic:'/ˈæpəl/', position:1 },
      { id:'en-b', char:'B', lower:'b', name:'B', sound:'b', ipa:'/b/', example:'Bird', examplePhonetic:'/bɜːrd/', position:2 },
      { id:'en-c', char:'C', lower:'c', name:'C', sound:'k / s', ipa:'/k/ or /s/', example:'Cat', examplePhonetic:'/kæt/', position:3 },
      { id:'en-d', char:'D', lower:'d', name:'D', sound:'d', ipa:'/d/', example:'Dog', examplePhonetic:'/dɒɡ/', position:4 },
      { id:'en-e', char:'E', lower:'e', name:'E', sound:'ɛ / iː', ipa:'/ɛ/', example:'Elephant', examplePhonetic:'/ˈɛlɪfənt/', position:5 },
      { id:'en-f', char:'F', lower:'f', name:'F', sound:'f', ipa:'/f/', example:'Fish', examplePhonetic:'/fɪʃ/', position:6 },
      { id:'en-g', char:'G', lower:'g', name:'G', sound:'ɡ / dʒ', ipa:'/ɡ/', example:'Gold', examplePhonetic:'/ɡoʊld/', position:7 },
      { id:'en-h', char:'H', lower:'h', name:'H', sound:'h', ipa:'/h/', example:'House', examplePhonetic:'/haʊs/', position:8 },
      { id:'en-i', char:'I', lower:'i', name:'I', sound:'ɪ / aɪ', ipa:'/ɪ/', example:'Island', examplePhonetic:'/ˈaɪlənd/', position:9 },
      { id:'en-j', char:'J', lower:'j', name:'J', sound:'dʒ', ipa:'/dʒ/', example:'Jungle', examplePhonetic:'/ˈdʒʌŋɡəl/', position:10 },
      { id:'en-k', char:'K', lower:'k', name:'K', sound:'k', ipa:'/k/', example:'King', examplePhonetic:'/kɪŋ/', position:11 },
      { id:'en-l', char:'L', lower:'l', name:'L', sound:'l', ipa:'/l/', example:'Lion', examplePhonetic:'/ˈlaɪən/', position:12 },
      { id:'en-m', char:'M', lower:'m', name:'M', sound:'m', ipa:'/m/', example:'Moon', examplePhonetic:'/muːn/', position:13 },
      { id:'en-n', char:'N', lower:'n', name:'N', sound:'n', ipa:'/n/', example:'Night', examplePhonetic:'/naɪt/', position:14 },
      { id:'en-o', char:'O', lower:'o', name:'O', sound:'ɒ / oʊ', ipa:'/ɒ/', example:'Ocean', examplePhonetic:'/ˈoʊʃən/', position:15 },
      { id:'en-p', char:'P', lower:'p', name:'P', sound:'p', ipa:'/p/', example:'Planet', examplePhonetic:'/ˈplænɪt/', position:16 },
      { id:'en-q', char:'Q', lower:'q', name:'Q', sound:'kw', ipa:'/kw/', example:'Queen', examplePhonetic:'/kwiːn/', position:17 },
      { id:'en-r', char:'R', lower:'r', name:'R', sound:'ɹ', ipa:'/ɹ/', example:'River', examplePhonetic:'/ˈrɪvər/', position:18 },
      { id:'en-s', char:'S', lower:'s', name:'S', sound:'s / z', ipa:'/s/', example:'Star', examplePhonetic:'/stɑːr/', position:19 },
      { id:'en-t', char:'T', lower:'t', name:'T', sound:'t', ipa:'/t/', example:'Tree', examplePhonetic:'/triː/', position:20 },
      { id:'en-u', char:'U', lower:'u', name:'U', sound:'ʌ / juː', ipa:'/ʌ/', example:'Under', examplePhonetic:'/ˈʌndər/', position:21 },
      { id:'en-v', char:'V', lower:'v', name:'V', sound:'v', ipa:'/v/', example:'Voice', examplePhonetic:'/vɔɪs/', position:22 },
      { id:'en-w', char:'W', lower:'w', name:'W', sound:'w', ipa:'/w/', example:'Water', examplePhonetic:'/ˈwɔːtər/', position:23 },
      { id:'en-x', char:'X', lower:'x', name:'X', sound:'ks / z', ipa:'/ks/', example:'Xenon', examplePhonetic:'/ˈziːnɒn/', position:24 },
      { id:'en-y', char:'Y', lower:'y', name:'Y', sound:'j / aɪ', ipa:'/j/', example:'Yellow', examplePhonetic:'/ˈjɛloʊ/', position:25 },
      { id:'en-z', char:'Z', lower:'z', name:'Z', sound:'z', ipa:'/z/', example:'Zebra', examplePhonetic:'/ˈziːbrə/', position:26 },
    ]
  },

  hebrew: {
    id: 'hebrew',
    name: 'Hebrew',
    nativeName: 'עברית',
    accentClass: 'accent-hebrew',
    color: '#f59e0b',
    direction: 'rtl',
    langCode: 'he-IL',
    voiceLang: 'he',
    description: 'The Hebrew alphabet (אָלֶף-בֵּית) consists of 22 consonants. Vowels are typically indicated by diacritics called nikud.',
    historicalNote: 'One of the oldest alphabets, descended from the Phoenician script. Modern Hebrew was revived in the 19th-20th centuries from ancient Biblical Hebrew.',
    letters: [
      { id:'he-alef',  char:'א', lower:'א', name:'Alef',  sound:'silent / ʔ', ipa:'/ʔ/', example:'אָב (av — father)', examplePhonetic:'/av/', position:1 },
      { id:'he-bet',   char:'בּ', lower:'ב', name:'Bet / Vet', sound:'b / v', ipa:'/b/ or /v/', example:'בַּיִת (bayit — house)', examplePhonetic:'/ˈbajɪt/', position:2 },
      { id:'he-gimel', char:'ג', lower:'ג', name:'Gimel', sound:'g', ipa:'/ɡ/', example:'גַּן (gan — garden)', examplePhonetic:'/ɡan/', position:3 },
      { id:'he-dalet', char:'ד', lower:'ד', name:'Dalet', sound:'d', ipa:'/d/', example:'דָּג (dag — fish)', examplePhonetic:'/daɡ/', position:4 },
      { id:'he-he',    char:'ה', lower:'ה', name:'He',    sound:'h', ipa:'/h/', example:'הַר (har — mountain)', examplePhonetic:'/har/', position:5 },
      { id:'he-vav',   char:'ו', lower:'ו', name:'Vav',   sound:'v / w', ipa:'/v/', example:'וָרֶד (vared — rose)', examplePhonetic:'/vaˈɾed/', position:6 },
      { id:'he-zayin', char:'ז', lower:'ז', name:'Zayin', sound:'z', ipa:'/z/', example:'זְמַן (zman — time)', examplePhonetic:'/zman/', position:7 },
      { id:'he-het',   char:'ח', lower:'ח', name:'Khet',  sound:'x', ipa:'/χ/', example:'חַי (khai — alive)', examplePhonetic:'/χaj/', position:8 },
      { id:'he-tet',   char:'ט', lower:'ט', name:'Tet',   sound:'t', ipa:'/t/', example:'טוֹב (tov — good)', examplePhonetic:'/tov/', position:9 },
      { id:'he-yod',   char:'י', lower:'י', name:'Yod',   sound:'j', ipa:'/j/', example:'יָם (yam — sea)', examplePhonetic:'/jam/', position:10 },
      { id:'he-kaf',   char:'כּ', lower:'כ', name:'Kaf / Khaf', sound:'k / x', ipa:'/k/ or /χ/', example:'כֶּלֶב (kelev — dog)', examplePhonetic:'/ˈkelev/', position:11 },
      { id:'he-lamed', char:'ל', lower:'ל', name:'Lamed', sound:'l', ipa:'/l/', example:'לֶחֶם (lekhem — bread)', examplePhonetic:'/ˈleχem/', position:12 },
      { id:'he-mem',   char:'מ', lower:'מ', name:'Mem',   sound:'m', ipa:'/m/', example:'מַיִם (mayim — water)', examplePhonetic:'/ˈmajɪm/', position:13 },
      { id:'he-nun',   char:'נ', lower:'נ', name:'Nun',   sound:'n', ipa:'/n/', example:'נֵר (ner — candle)', examplePhonetic:'/neɾ/', position:14 },
      { id:'he-samekh',char:'ס', lower:'ס', name:'Samekh',sound:'s', ipa:'/s/', example:'סֵפֶר (sefer — book)', examplePhonetic:'/ˈsefeɾ/', position:15 },
      { id:'he-ayin',  char:'ע', lower:'ע', name:'Ayin',  sound:'ʕ / silent', ipa:'/ʕ/', example:'עַיִן (ayin — eye)', examplePhonetic:'/ˈʕajɪn/', position:16 },
      { id:'he-pe',    char:'פּ', lower:'פ', name:'Pe / Fe', sound:'p / f', ipa:'/p/ or /f/', example:'פֶּה (peh — mouth)', examplePhonetic:'/pe/', position:17 },
      { id:'he-tsadi', char:'צ', lower:'צ', name:'Tsadi', sound:'ts', ipa:'/ts/', example:'צִפּוֹר (tsipor — bird)', examplePhonetic:'/tsiˈpoɾ/', position:18 },
      { id:'he-qof',   char:'ק', lower:'ק', name:'Qof',   sound:'k', ipa:'/k/', example:'קוֹל (kol — voice)', examplePhonetic:'/kol/', position:19 },
      { id:'he-resh',  char:'ר', lower:'ר', name:'Resh',  sound:'ʁ', ipa:'/ʁ/', example:'רֶגֶל (regel — leg)', examplePhonetic:'/ˈʁeɡel/', position:20 },
      { id:'he-shin',  char:'שׁ', lower:'ש', name:'Shin / Sin', sound:'ʃ / s', ipa:'/ʃ/ or /s/', example:'שֶׁמֶשׁ (shemesh — sun)', examplePhonetic:'/ˈʃemeʃ/', position:21 },
      { id:'he-tav',   char:'ת', lower:'ת', name:'Tav',   sound:'t', ipa:'/t/', example:'תַּפּוּחַ (tapuakh — apple)', examplePhonetic:'/taˈpuaχ/', position:22 },
    ]
  },

  bulgarian: {
    id: 'bulgarian',
    name: 'Bulgarian',
    nativeName: 'Български',
    accentClass: 'accent-bulgarian',
    color: '#22d3ee',
    direction: 'ltr',
    langCode: 'bg-BG',
    voiceLang: 'bg',
    description: 'Bulgarian uses the Cyrillic alphabet with 30 letters, making it the first Slavic language to use Cyrillic in literary form.',
    historicalNote: 'The Bulgarian Cyrillic alphabet was codified in medieval Bulgaria and spread throughout the Slavic world via Orthodox Christianity.',
    letters: [
      { id:'bg-a',  char:'А', lower:'а', name:'А (A)',   sound:'a',  ipa:'/a/', example:'Азбука (azbuka — alphabet)', examplePhonetic:'/ˈazbuka/', position:1 },
      { id:'bg-b',  char:'Б', lower:'б', name:'Б (Be)',  sound:'b',  ipa:'/b/', example:'Баща (bashta — father)', examplePhonetic:'/baʃta/', position:2 },
      { id:'bg-v',  char:'В', lower:'в', name:'В (Ve)',  sound:'v',  ipa:'/v/', example:'Вода (voda — water)', examplePhonetic:'/voda/', position:3 },
      { id:'bg-g',  char:'Г', lower:'г', name:'Г (Ge)',  sound:'g',  ipa:'/ɡ/', example:'Гора (gora — forest)', examplePhonetic:'/ɡora/', position:4 },
      { id:'bg-d',  char:'Д', lower:'д', name:'Д (De)',  sound:'d',  ipa:'/d/', example:'Дом (dom — home)', examplePhonetic:'/dom/', position:5 },
      { id:'bg-e',  char:'Е', lower:'е', name:'Е (E)',   sound:'ɛ',  ipa:'/ɛ/', example:'Езеро (ezero — lake)', examplePhonetic:'/ˈɛzɛro/', position:6 },
      { id:'bg-zh', char:'Ж', lower:'ж', name:'Ж (Zhe)', sound:'ʒ',  ipa:'/ʒ/', example:'Жена (zhena — woman)', examplePhonetic:'/ʒɛna/', position:7 },
      { id:'bg-z',  char:'З', lower:'з', name:'З (Ze)',  sound:'z',  ipa:'/z/', example:'Земя (zemya — earth)', examplePhonetic:'/zɛˈmja/', position:8 },
      { id:'bg-i',  char:'И', lower:'и', name:'И (I)',   sound:'i',  ipa:'/i/', example:'Игла (igla — needle)', examplePhonetic:'/ˈiɡla/', position:9 },
      { id:'bg-y',  char:'Й', lower:'й', name:'Й (Kratko I)', sound:'j', ipa:'/j/', example:'Чай (chai — tea)', examplePhonetic:'/tʃaj/', position:10 },
      { id:'bg-k',  char:'К', lower:'к', name:'К (Ka)',  sound:'k',  ipa:'/k/', example:'Книга (kniga — book)', examplePhonetic:'/ˈknɪɡa/', position:11 },
      { id:'bg-l',  char:'Л', lower:'л', name:'Л (El)',  sound:'l',  ipa:'/l/', example:'Луна (luna — moon)', examplePhonetic:'/luna/', position:12 },
      { id:'bg-m',  char:'М', lower:'м', name:'М (Em)',  sound:'m',  ipa:'/m/', example:'Море (more — sea)', examplePhonetic:'/morɛ/', position:13 },
      { id:'bg-n',  char:'Н', lower:'н', name:'Н (En)',  sound:'n',  ipa:'/n/', example:'Нощ (nosht — night)', examplePhonetic:'/noʃt/', position:14 },
      { id:'bg-o',  char:'О', lower:'о', name:'О (O)',   sound:'o',  ipa:'/o/', example:'Огън (ogan — fire)', examplePhonetic:'/ˈoɡɐn/', position:15 },
      { id:'bg-p',  char:'П', lower:'п', name:'П (Pe)',  sound:'p',  ipa:'/p/', example:'Птица (ptitsa — bird)', examplePhonetic:'/ˈptɪtsa/', position:16 },
      { id:'bg-r',  char:'Р', lower:'р', name:'Р (Er)',  sound:'r',  ipa:'/r/', example:'Река (reka — river)', examplePhonetic:'/rɛˈka/', position:17 },
      { id:'bg-s',  char:'С', lower:'с', name:'С (Es)',  sound:'s',  ipa:'/s/', example:'Слънце (slantse — sun)', examplePhonetic:'/ˈslɐntse/', position:18 },
      { id:'bg-t',  char:'Т', lower:'т', name:'Т (Te)',  sound:'t',  ipa:'/t/', example:'Топло (toplo — warm)', examplePhonetic:'/ˈtoplo/', position:19 },
      { id:'bg-u',  char:'У', lower:'у', name:'У (U)',   sound:'u',  ipa:'/u/', example:'Улица (ulitsa — street)', examplePhonetic:'/ˈulɪtsa/', position:20 },
      { id:'bg-f',  char:'Ф', lower:'ф', name:'Ф (Ef)',  sound:'f',  ipa:'/f/', example:'Фар (far — lighthouse)', examplePhonetic:'/far/', position:21 },
      { id:'bg-h',  char:'Х', lower:'х', name:'Х (Ha)',  sound:'x',  ipa:'/x/', example:'Хляб (khlyab — bread)', examplePhonetic:'/xljab/', position:22 },
      { id:'bg-ts', char:'Ц', lower:'ц', name:'Ц (Tse)', sound:'ts', ipa:'/ts/', example:'Цвете (tsvete — flower)', examplePhonetic:'/tsˈvɛtɛ/', position:23 },
      { id:'bg-ch', char:'Ч', lower:'ч', name:'Ч (Che)', sound:'tʃ', ipa:'/tʃ/', example:'Черно (cherno — black)', examplePhonetic:'/ˈtʃɛrno/', position:24 },
      { id:'bg-sh', char:'Ш', lower:'ш', name:'Ш (Sha)', sound:'ʃ',  ipa:'/ʃ/', example:'Шума (shuma — noise)', examplePhonetic:'/ˈʃuma/', position:25 },
      { id:'bg-sht',char:'Щ', lower:'щ', name:'Щ (Shta)', sound:'ʃt', ipa:'/ʃt/', example:'Щастие (shtastie — happiness)', examplePhonetic:'/ˈʃtastɪɛ/', position:26 },
      { id:'bg-yu', char:'Ъ', lower:'ъ', name:'Ъ (Er Gol)', sound:'ɐ', ipa:'/ɐ/', example:'Ъгъл (agal — corner)', examplePhonetic:'/ˈɐɡɐl/', position:27 },
      { id:'bg-yf', char:'Ь', lower:'ь', name:'Ь (Er Mal)', sound:'j (softener)', ipa:'/ʲ/', example:'Шьо (rare)', examplePhonetic:'', position:28 },
      { id:'bg-yu2',char:'Ю', lower:'ю', name:'Ю (Yu)',  sound:'ju', ipa:'/ju/', example:'Юг (yug — south)', examplePhonetic:'/juɡ/', position:29 },
      { id:'bg-ya', char:'Я', lower:'я', name:'Я (Ya)',  sound:'ja', ipa:'/ja/', example:'Ябълка (yabylka — apple)', examplePhonetic:'/ˈjabɐlka/', position:30 },
    ]
  },

  russian: {
    id: 'russian',
    name: 'Russian',
    nativeName: 'Русский',
    accentClass: 'accent-russian',
    color: '#f43f5e',
    direction: 'ltr',
    langCode: 'ru-RU',
    voiceLang: 'ru',
    description: 'The Russian Cyrillic alphabet has 33 letters and is the native writing system of the most widely spoken Slavic language.',
    historicalNote: 'Russian Cyrillic was reformed by Peter the Great in 1708 and again after the 1917 revolution, resulting in the modern 33-letter alphabet.',
    letters: [
      { id:'ru-a',  char:'А', lower:'а', name:'А (A)',    sound:'a',   ipa:'/a/', example:'Автобус (avtobus — bus)', examplePhonetic:'/ɐvˈtobʊs/', position:1 },
      { id:'ru-b',  char:'Б', lower:'б', name:'Б (Be)',   sound:'b',   ipa:'/b/', example:'Берег (bereg — shore)', examplePhonetic:'/ˈbʲerʲɪk/', position:2 },
      { id:'ru-v',  char:'В', lower:'в', name:'В (Ve)',   sound:'v',   ipa:'/v/', example:'Вода (voda — water)', examplePhonetic:'/vɐˈda/', position:3 },
      { id:'ru-g',  char:'Г', lower:'г', name:'Г (Ge)',   sound:'g',   ipa:'/ɡ/', example:'Город (gorod — city)', examplePhonetic:'/ˈɡorət/', position:4 },
      { id:'ru-d',  char:'Д', lower:'д', name:'Д (De)',   sound:'d',   ipa:'/d/', example:'Дерево (derevo — tree)', examplePhonetic:'/ˈdʲerʲɪvə/', position:5 },
      { id:'ru-ye', char:'Е', lower:'е', name:'Е (Ye)',   sound:'je',  ipa:'/je/', example:'Если (yesli — if)', examplePhonetic:'/ˈjesʲlʲɪ/', position:6 },
      { id:'ru-yo', char:'Ё', lower:'ё', name:'Ё (Yo)',   sound:'jo',  ipa:'/jo/', example:'Ёж (yozh — hedgehog)', examplePhonetic:'/joʂ/', position:7 },
      { id:'ru-zh', char:'Ж', lower:'ж', name:'Ж (Zhe)',  sound:'ʒ',   ipa:'/ʒ/', example:'Жизнь (zhizn — life)', examplePhonetic:'/ʐɨzʲnʲ/', position:8 },
      { id:'ru-z',  char:'З', lower:'з', name:'З (Ze)',   sound:'z',   ipa:'/z/', example:'Звезда (zvezda — star)', examplePhonetic:'/zvʲɪzˈda/', position:9 },
      { id:'ru-i',  char:'И', lower:'и', name:'И (I)',    sound:'i',   ipa:'/i/', example:'Имя (imya — name)', examplePhonetic:'/ˈimʲə/', position:10 },
      { id:'ru-yk', char:'Й', lower:'й', name:'Й (Kratkoye I)', sound:'j', ipa:'/j/', example:'Чайник (chaynik — kettle)', examplePhonetic:'/ˈtʂajnʲɪk/', position:11 },
      { id:'ru-k',  char:'К', lower:'к', name:'К (Ka)',   sound:'k',   ipa:'/k/', example:'Книга (kniga — book)', examplePhonetic:'/ˈknʲiɡə/', position:12 },
      { id:'ru-l',  char:'Л', lower:'л', name:'Л (El)',   sound:'l',   ipa:'/l/', example:'Луна (luna — moon)', examplePhonetic:'/lʊˈna/', position:13 },
      { id:'ru-m',  char:'М', lower:'м', name:'М (Em)',   sound:'m',   ipa:'/m/', example:'Море (more — sea)', examplePhonetic:'/ˈmorʲɪ/', position:14 },
      { id:'ru-n',  char:'Н', lower:'н', name:'Н (En)',   sound:'n',   ipa:'/n/', example:'Ночь (noch — night)', examplePhonetic:'/notɕ/', position:15 },
      { id:'ru-o',  char:'О', lower:'о', name:'О (O)',    sound:'o',   ipa:'/o/', example:'Окно (okno — window)', examplePhonetic:'/ɐkˈno/', position:16 },
      { id:'ru-p',  char:'П', lower:'п', name:'П (Pe)',   sound:'p',   ipa:'/p/', example:'Поле (pole — field)', examplePhonetic:'/ˈpolʲɪ/', position:17 },
      { id:'ru-r',  char:'Р', lower:'р', name:'Р (Er)',   sound:'r',   ipa:'/r/', example:'Река (reka — river)', examplePhonetic:'/rʲɪˈka/', position:18 },
      { id:'ru-s',  char:'С', lower:'с', name:'С (Es)',   sound:'s',   ipa:'/s/', example:'Солнце (solntse — sun)', examplePhonetic:'/ˈsontsɨ/', position:19 },
      { id:'ru-t',  char:'Т', lower:'т', name:'Т (Te)',   sound:'t',   ipa:'/t/', example:'Тигр (tigr — tiger)', examplePhonetic:'/tʲiɡr/', position:20 },
      { id:'ru-u',  char:'У', lower:'у', name:'У (U)',    sound:'u',   ipa:'/u/', example:'Улица (ulitsa — street)', examplePhonetic:'/ˈulʲɪtsə/', position:21 },
      { id:'ru-f',  char:'Ф', lower:'ф', name:'Ф (Ef)',   sound:'f',   ipa:'/f/', example:'Фонтан (fontan — fountain)', examplePhonetic:'/fɐnˈtan/', position:22 },
      { id:'ru-kh', char:'Х', lower:'х', name:'Х (Kha)',  sound:'x',   ipa:'/x/', example:'Хлеб (khleb — bread)', examplePhonetic:'/xlʲeb/', position:23 },
      { id:'ru-ts', char:'Ц', lower:'ц', name:'Ц (Tse)',  sound:'ts',  ipa:'/ts/', example:'Цвет (tsvet — color)', examplePhonetic:'/tsvʲet/', position:24 },
      { id:'ru-ch', char:'Ч', lower:'ч', name:'Ч (Che)',  sound:'tɕ',  ipa:'/tɕ/', example:'Час (chas — hour)', examplePhonetic:'/tɕas/', position:25 },
      { id:'ru-sh', char:'Ш', lower:'ш', name:'Ш (Sha)',  sound:'ʂ',   ipa:'/ʂ/', example:'Школа (shkola — school)', examplePhonetic:'/ˈʂkolə/', position:26 },
      { id:'ru-sch',char:'Щ', lower:'щ', name:'Щ (Shcha)', sound:'ɕɕ', ipa:'/ɕɕ/', example:'Щи (shchi — cabbage soup)', examplePhonetic:'/ɕːi/', position:27 },
      { id:'ru-hd', char:'Ъ', lower:'ъ', name:'Ъ (Hard Sign)', sound:'(separator)', ipa:'', example:'Объект (obekt — object)', examplePhonetic:'/ɐbˈjekt/', position:28 },
      { id:'ru-iy', char:'Ы', lower:'ы', name:'Ы (Yeru)', sound:'ɨ',   ipa:'/ɨ/', example:'Рыба (ryba — fish)', examplePhonetic:'/ˈrɨbə/', position:29 },
      { id:'ru-sf', char:'Ь', lower:'ь', name:'Ь (Soft Sign)', sound:'(palatalizer)', ipa:'/ʲ/', example:'Мать (mat — mother)', examplePhonetic:'/matʲ/', position:30 },
      { id:'ru-e',  char:'Э', lower:'э', name:'Э (E)',    sound:'e',   ipa:'/e/', example:'Эхо (ekho — echo)', examplePhonetic:'/ˈexə/', position:31 },
      { id:'ru-yu', char:'Ю', lower:'ю', name:'Ю (Yu)',   sound:'ju',  ipa:'/ju/', example:'Юг (yug — south)', examplePhonetic:'/juk/', position:32 },
      { id:'ru-ya', char:'Я', lower:'я', name:'Я (Ya)',   sound:'ja',  ipa:'/ja/', example:'Яблоко (yabloko — apple)', examplePhonetic:'/ˈjabləkə/', position:33 },
    ]
  },

  greekModern: {
    id: 'greekModern',
    name: 'Greek (Modern)',
    nativeName: 'Ελληνικά',
    accentClass: 'accent-greek-modern',
    color: '#34d399',
    direction: 'ltr',
    langCode: 'el-GR',
    voiceLang: 'el',
    description: 'The Modern Greek alphabet has 24 letters and is the direct ancestor of the Latin and Cyrillic alphabets.',
    historicalNote: 'Modern Greek (Standard Modern Greek) evolved from Koine Greek and Byzantine Greek. The alphabet remains unchanged since antiquity, though pronunciation has shifted significantly.',
    letters: [
      { id:'gm-alpha',   char:'Α', lower:'α', name:'Alpha',   sound:'a',  ipa:'/a/', example:'Αγάπη (agapi — love)', examplePhonetic:'/aˈɣapi/', position:1 },
      { id:'gm-beta',    char:'Β', lower:'β', name:'Beta',    sound:'v',  ipa:'/v/', example:'Βιβλίο (vivlio — book)', examplePhonetic:'/viˈvlio/', position:2 },
      { id:'gm-gamma',   char:'Γ', lower:'γ', name:'Gamma',   sound:'ɣ / j', ipa:'/ɣ/', example:'Γάτα (gata — cat)', examplePhonetic:'/ˈɣata/', position:3 },
      { id:'gm-delta',   char:'Δ', lower:'δ', name:'Delta',   sound:'ð',  ipa:'/ð/', example:'Δέντρο (dentro — tree)', examplePhonetic:'/ˈðendro/', position:4 },
      { id:'gm-epsilon', char:'Ε', lower:'ε', name:'Epsilon', sound:'e',  ipa:'/e/', example:'Ελιά (elia — olive)', examplePhonetic:'/eˈlja/', position:5 },
      { id:'gm-zeta',    char:'Ζ', lower:'ζ', name:'Zeta',    sound:'z',  ipa:'/z/', example:'Ζωή (zoi — life)', examplePhonetic:'/zoˈi/', position:6 },
      { id:'gm-eta',     char:'Η', lower:'η', name:'Eta',     sound:'i',  ipa:'/i/', example:'Ήλιος (ilios — sun)', examplePhonetic:'/ˈilios/', position:7 },
      { id:'gm-theta',   char:'Θ', lower:'θ', name:'Theta',   sound:'θ',  ipa:'/θ/', example:'Θάλασσα (thalassa — sea)', examplePhonetic:'/ˈθalasa/', position:8 },
      { id:'gm-iota',    char:'Ι', lower:'ι', name:'Iota',    sound:'i',  ipa:'/i/', example:'Ιδέα (idea — idea)', examplePhonetic:'/iˈðea/', position:9 },
      { id:'gm-kappa',   char:'Κ', lower:'κ', name:'Kappa',   sound:'k',  ipa:'/k/', example:'Καρδιά (kardia — heart)', examplePhonetic:'/karˈðja/', position:10 },
      { id:'gm-lambda',  char:'Λ', lower:'λ', name:'Lambda',  sound:'l',  ipa:'/l/', example:'Λόγος (logos — word)', examplePhonetic:'/ˈloɣos/', position:11 },
      { id:'gm-mu',      char:'Μ', lower:'μ', name:'Mu',      sound:'m',  ipa:'/m/', example:'Μάτι (mati — eye)', examplePhonetic:'/ˈmati/', position:12 },
      { id:'gm-nu',      char:'Ν', lower:'ν', name:'Nu',      sound:'n',  ipa:'/n/', example:'Νερό (nero — water)', examplePhonetic:'/neˈro/', position:13 },
      { id:'gm-xi',      char:'Ξ', lower:'ξ', name:'Xi',      sound:'ks', ipa:'/ks/', example:'Ξύλο (xylo — wood)', examplePhonetic:'/ˈksilo/', position:14 },
      { id:'gm-omicron', char:'Ο', lower:'ο', name:'Omicron', sound:'o',  ipa:'/o/', example:'Ουρανός (ouranos — sky)', examplePhonetic:'/uraˈnos/', position:15 },
      { id:'gm-pi',      char:'Π', lower:'π', name:'Pi',      sound:'p',  ipa:'/p/', example:'Πάντα (panda — always)', examplePhonetic:'/ˈpanda/', position:16 },
      { id:'gm-rho',     char:'Ρ', lower:'ρ', name:'Rho',     sound:'r',  ipa:'/r/', example:'Ρόδο (rodo — rose)', examplePhonetic:'/ˈroðo/', position:17 },
      { id:'gm-sigma',   char:'Σ', lower:'σ', name:'Sigma',   sound:'s',  ipa:'/s/', example:'Σπίτι (spiti — house)', examplePhonetic:'/ˈspiti/', position:18 },
      { id:'gm-tau',     char:'Τ', lower:'τ', name:'Tau',     sound:'t',  ipa:'/t/', example:'Τόπος (topos — place)', examplePhonetic:'/ˈtopos/', position:19 },
      { id:'gm-upsilon', char:'Υ', lower:'υ', name:'Upsilon', sound:'i',  ipa:'/i/', example:'Υπάρχω (yparcho — I exist)', examplePhonetic:'/iˈparxo/', position:20 },
      { id:'gm-phi',     char:'Φ', lower:'φ', name:'Phi',     sound:'f',  ipa:'/f/', example:'Φως (fos — light)', examplePhonetic:'/fos/', position:21 },
      { id:'gm-chi',     char:'Χ', lower:'χ', name:'Chi',     sound:'x / ç', ipa:'/x/', example:'Χρόνος (chronos — time)', examplePhonetic:'/ˈxronos/', position:22 },
      { id:'gm-psi',     char:'Ψ', lower:'ψ', name:'Psi',     sound:'ps', ipa:'/ps/', example:'Ψάρι (psari — fish)', examplePhonetic:'/ˈpsari/', position:23 },
      { id:'gm-omega',   char:'Ω', lower:'ω', name:'Omega',   sound:'o',  ipa:'/o/', example:'Ώρα (ora — hour)', examplePhonetic:'/ˈora/', position:24 },
    ]
  },

  greekAncient: {
    id: 'greekAncient',
    name: 'Greek (Ancient)',
    nativeName: 'Ἀρχαία Ἑλληνική',
    accentClass: 'accent-greek-ancient',
    color: '#a78bfa',
    direction: 'ltr',
    badge: 'Attic / Classical',
    langCode: 'el-GR',        // closest available; Ancient Greek has no browser TTS
    voiceLang: 'el',
    description: 'Ancient (Attic) Greek uses the same 24-letter alphabet but with distinct classical pronunciation. Vowels carry length distinctions and pitch accents.',
    historicalNote: 'Attic Greek was the prestige dialect of Classical Athens (5th–4th c. BCE), the language of Plato, Thucydides, and the tragedians. Its pronunciation differed markedly from Modern Greek — eta (η) was a long /ɛː/ not /i/, beta (β) was /b/ not /v/, and pitch accent carried grammatical meaning.',
    letters: [
      { id:'ga-alpha',   char:'Α', lower:'α', name:'Alpha',   sound:'a / aː', ipa:'/a/ or /aː/', example:'ἀγαθός (agathos — good)', examplePhonetic:'/aɡaˈtʰos/', position:1 },
      { id:'ga-beta',    char:'Β', lower:'β', name:'Beta',    sound:'b',      ipa:'/b/', example:'βίος (bios — life)', examplePhonetic:'/ˈbios/', position:2 },
      { id:'ga-gamma',   char:'Γ', lower:'γ', name:'Gamma',   sound:'ɡ / ŋ', ipa:'/ɡ/', example:'γῆ (gē — earth)', examplePhonetic:'/ɡɛː/', position:3 },
      { id:'ga-delta',   char:'Δ', lower:'δ', name:'Delta',   sound:'d',      ipa:'/d/', example:'δῆμος (dēmos — people)', examplePhonetic:'/ˈdɛːmos/', position:4 },
      { id:'ga-epsilon', char:'Ε', lower:'ε', name:'Epsilon', sound:'e (short)', ipa:'/e/', example:'ἔργον (ergon — work)', examplePhonetic:'/ˈerɡon/', position:5 },
      { id:'ga-zeta',    char:'Ζ', lower:'ζ', name:'Zeta',    sound:'zd / dz', ipa:'/zd/', example:'ζωή (zōē — life)', examplePhonetic:'/zdɔːˈɛː/', position:6 },
      { id:'ga-eta',     char:'Η', lower:'η', name:'Eta',     sound:'ɛː (long e)', ipa:'/ɛː/', example:'ἦθος (ēthos — character)', examplePhonetic:'/ˈɛːtʰos/', position:7 },
      { id:'ga-theta',   char:'Θ', lower:'θ', name:'Theta',   sound:'tʰ (aspirated t)', ipa:'/tʰ/', example:'θεός (theos — god)', examplePhonetic:'/tʰeˈos/', position:8 },
      { id:'ga-iota',    char:'Ι', lower:'ι', name:'Iota',    sound:'i / iː', ipa:'/i/ or /iː/', example:'ἰδέα (idea — form)', examplePhonetic:'/iˈdeːa/', position:9 },
      { id:'ga-kappa',   char:'Κ', lower:'κ', name:'Kappa',   sound:'k',      ipa:'/k/', example:'κόσμος (kosmos — order/world)', examplePhonetic:'/ˈkosmos/', position:10 },
      { id:'ga-lambda',  char:'Λ', lower:'λ', name:'Lambda',  sound:'l',      ipa:'/l/', example:'λόγος (logos — reason)', examplePhonetic:'/ˈloɡos/', position:11 },
      { id:'ga-mu',      char:'Μ', lower:'μ', name:'Mu',      sound:'m',      ipa:'/m/', example:'μῦθος (mythos — story)', examplePhonetic:'/ˈmyːtʰos/', position:12 },
      { id:'ga-nu',      char:'Ν', lower:'ν', name:'Nu',      sound:'n',      ipa:'/n/', example:'νόμος (nomos — law)', examplePhonetic:'/ˈnomos/', position:13 },
      { id:'ga-xi',      char:'Ξ', lower:'ξ', name:'Xi',      sound:'ks',     ipa:'/ks/', example:'ξένος (xenos — stranger)', examplePhonetic:'/ˈksenos/', position:14 },
      { id:'ga-omicron', char:'Ο', lower:'ο', name:'Omicron', sound:'o (short)', ipa:'/o/', example:'ὄνομα (onoma — name)', examplePhonetic:'/ˈonoma/', position:15 },
      { id:'ga-pi',      char:'Π', lower:'π', name:'Pi',      sound:'p',      ipa:'/p/', example:'πόλις (polis — city-state)', examplePhonetic:'/ˈpolis/', position:16 },
      { id:'ga-rho',     char:'Ρ', lower:'ρ', name:'Rho',     sound:'r',      ipa:'/r/', example:'ῥήτωρ (rhētor — orator)', examplePhonetic:'/ˈrɛːtɔːr/', position:17 },
      { id:'ga-sigma',   char:'Σ', lower:'σ/ς', name:'Sigma', sound:'s',      ipa:'/s/', example:'σοφία (sophia — wisdom)', examplePhonetic:'/soˈpʰia/', position:18 },
      { id:'ga-tau',     char:'Τ', lower:'τ', name:'Tau',     sound:'t',      ipa:'/t/', example:'τύχη (tyche — fortune)', examplePhonetic:'/ˈtyːkʰɛː/', position:19 },
      { id:'ga-upsilon', char:'Υ', lower:'υ', name:'Upsilon', sound:'y / yː', ipa:'/y/', example:'ὕβρις (hybris — arrogance)', examplePhonetic:'/ˈhybris/', position:20 },
      { id:'ga-phi',     char:'Φ', lower:'φ', name:'Phi',     sound:'pʰ (aspirated p)', ipa:'/pʰ/', example:'φιλοσοφία (philosophia — philosophy)', examplePhonetic:'/pʰilosopʰˈia/', position:21 },
      { id:'ga-chi',     char:'Χ', lower:'χ', name:'Chi',     sound:'kʰ (aspirated k)', ipa:'/kʰ/', example:'χρόνος (chronos — time)', examplePhonetic:'/ˈkʰronos/', position:22 },
      { id:'ga-psi',     char:'Ψ', lower:'ψ', name:'Psi',     sound:'ps',     ipa:'/ps/', example:'ψυχή (psychē — soul)', examplePhonetic:'/psyˈkʰɛː/', position:23 },
      { id:'ga-omega',   char:'Ω', lower:'ω', name:'Omega',   sound:'ɔː (long o)', ipa:'/ɔː/', example:'ὠκεανός (ōkeanos — ocean)', examplePhonetic:'/ɔːkeaˈnos/', position:24 },
    ]
  },
}

export const ALPHABET_LIST = Object.values(ALPHABETS)

export const getAlphabet = (id) => ALPHABETS[id] ?? null
export const getLetter   = (alphabetId, letterId) =>
  ALPHABETS[alphabetId]?.letters.find(l => l.id === letterId) ?? null

export function getPhoneticTTS(sound) {
  const map = {
    'a': 'ah',
    'a / aː': 'ah, or aah',
    'b': 'buh',
    'b / v': 'buh, or vuh',
    'd': 'duh',
    'dʒ': 'juh',
    'e': 'eh',
    'e (short)': 'eh',
    'f': 'fuh',
    'g': 'guh',
    'h': 'huh',
    'i': 'ee',
    'i / iː': 'ee',
    'j': 'yuh',
    'j (softener)': 'softens the previous consonant',
    'j / aɪ': 'yuh, or eye',
    'ja': 'yah',
    'je': 'yeh',
    'jo': 'yo',
    'ju': 'yoo',
    'k': 'kuh',
    'k / s': 'kuh, or suh',
    'k / x': 'kuh, or khuh',
    'ks': 'ks',
    'ks / z': 'ks, or zuh',
    'kw': 'kwuh',
    'kʰ (aspirated k)': 'kuh',
    'l': 'luh',
    'm': 'muh',
    'n': 'nuh',
    'o': 'oh',
    'o (short)': 'oh',
    'p': 'puh',
    'p / f': 'puh, or fuh',
    'ps': 'ps',
    'pʰ (aspirated p)': 'puh',
    'r': 'ruh',
    's': 'suh',
    's / z': 'suh, or zuh',
    'silent / ʔ': 'silent, or glottal stop',
    't': 'tuh',
    'ts': 'tsuh',
    'tɕ': 'chuh',
    'tʃ': 'chuh',
    'tʰ (aspirated t)': 'tuh',
    'u': 'oo',
    'v': 'vuh',
    'v / w': 'vuh, or wuh',
    'w': 'wuh',
    'x': 'khuh',
    'x / ç': 'khuh, or hue',
    'y / yː': 'ee',
    'z': 'zuh',
    'zd / dz': 'zd, or dz',
    'æ / eɪ': 'aah, or ay',
    'ð': 'thuh',
    'ɐ': 'uh',
    'ɒ / oʊ': 'aw, or oh',
    'ɔː (long o)': 'oh',
    'ɕɕ': 'shchuh',
    'ɛ': 'eh',
    'ɛ / iː': 'eh, or ee',
    'ɛː (long e)': 'eh',
    'ɡ / dʒ': 'guh, or juh',
    'ɡ / ŋ': 'guh, or ng',
    'ɣ / j': 'ghuh, or yuh',
    'ɨ': 'ih',
    'ɪ / aɪ': 'ih, or eye',
    'ɹ': 'ruh',
    'ʁ': 'ruh',
    'ʂ': 'shuh',
    'ʃ': 'shuh',
    'ʃ / s': 'shuh, or suh',
    'ʃt': 'shta',
    'ʌ / juː': 'uh, or yoo',
    'ʒ': 'zhuh',
    'ʕ / silent': 'glottal stop, or silent',
    'θ': 'thuh',
    '(palatalizer)': 'softens the previous consonant',
    '(separator)': 'separates syllables',
  };
  return map[sound] || sound;
}
